[package]
name = "rg-cli"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "rg"
path = "src/main.rs"

[dependencies]
clap.workspace = true
derive_more.workspace = true
rg-core = { path = "../core" }
